version: '3'
services:

  faxorderapp:
    build: app
    image: fax-order-dev:1.0
    container_name: fax-order-app
    environment:
      NODE_ENV: development
      #NODE_ENV: production
    env_file: .env
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
#    privileged: true
#    command: /sbin/init
#    tty: true
#    ports:
#      - 8080:8888
volumes:
  node_modules:
    driver: 'local'
