version: '3'
services:

  faxorderapp:
    build: app
    image: fax-order-dev:1.0
    container_name: fax-order-app
#    privileged: true
#    command: /sbin/init
#    tty: true
#    ports:
#      - 8080:8888
